services:

  mysql:
    container_name: "mysql"
    hostname: "mysql"
    image: mariadb:10.7.4
    restart: "always"
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysqladmin --user=$MYSQL_USER --password=$MYSQL_PASSWORD ping"
      interval: 3s
      timeout: 1s
      retries: 5
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./sql/go-queue.sql:/docker-entrypoint-initdb.d/go-queue.sql
