name: go-queue-sql_pull_request

on:
  pull_request:
    branches:
      - main
    paths:
      - "."
      - ".github/workflows/go-queue-sql_pull_request.yml"

jobs:
  go_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.19
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.51.1
          working-directory: .
          args: --verbose

  go_test:
    needs: [go_lint]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.19
      - name: Docker Start
        run: |
          docker compose up -d
      - name: Test go-queue-sql
        run: |
          cd /home/runner/work/go-queue-sql/go-queue-sql
          go mod download
          go test -v ./... -coverprofile /tmp/go-queue-sql.out | tee /tmp/go-queue-sql.log
      - name: Docker Clean-up
        run: |
          docker compose down
      - name: Upload artifacts (go_test)
        uses: actions/upload-artifact@v4
        with:
          name: go_test
          path: |
            /tmp/go-queue-sql.log
            /tmp/go-queue-sql.out
